# =============================================================================
# Exemplo: CI para projeto CODEBASE com Bun
# =============================================================================
# Copie este arquivo para .github/workflows/ci.yml no seu projeto
# =============================================================================

name: CI

on:
  pull_request:
    branches: [sandbox, main]
  push:
    branches: [sandbox, main]

jobs:
  ci:
    uses: iSmart-System/menura-actions/.github/workflows/codebase-ci-bun.yml@main
    with:
      bun-version: 'latest'
      # working-directory: '.'
      # artifact-path: 'dist'  # ou 'build', 'out', etc
      # skip-lint: false
      # skip-tests: false
      # skip-build: false
      # upload-artifacts: true  # false para desabilitar upload em PRs
    secrets: inherit
