# =============================================================================
# Exemplo: Release para projeto CODEBASE - Node.js
# =============================================================================
# Copie este arquivo para .github/workflows/release.yml no seu projeto
# Este workflow gera artefatos .zip e publica no GitHub Releases
# =============================================================================

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  release:
    uses: iSmart-System/menura-actions/.github/workflows/codebase-release-node.yml@main
    with:
      node-version: '20'
      build-command: 'npm run build'
      artifact-name: 'meu-projeto'
      artifact-path: 'dist'
      # working-directory: '.'
      # include-source: false
    secrets: inherit
