# =============================================================================
# Exemplo: CI para projeto Bun no GitLab
# =============================================================================
# Este exemplo mostra como usar os templates do m3nura/pipelines com Bun.
# Copie este arquivo para a raiz do seu projeto como .gitlab-ci.yml
# =============================================================================

include:
  # Include DIRETO do arquivo específico para Bun
  - project: 'm3nura/pipelines'
    ref: main
    file: '.gitlab/ci/codebase-ci-bun.yml'

# Definir stages
stages:
  - test
  - build

# Definir variáveis do projeto
variables:
  BUN_VERSION: "latest"
  ARTIFACT_PATH: "dist"
  ARTIFACT_NAME: "meu-app-bun"

# Job de lint (estende template do arquivo incluído)
lint:
  extends: .bun-lint

# Job de testes (estende template do arquivo incluído)
test:
  extends: .bun-test

# Job de build (estende template do arquivo incluído)
build:
  extends: .bun-build
