# =============================================================================
# Exemplo: CI Node.js pulando lint e testes
# =============================================================================
# Este exemplo é útil para projetos como Docusaurus que não têm lint/tests.
# Copie este arquivo para a raiz do seu projeto como .gitlab-ci.yml
# =============================================================================

# Workflow rules: controla quando a pipeline é executada
workflow:
  rules:
    # Permitir MRs (Merge Requests)
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    # Evitar duplicação se já existe MR aberto para a branch
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    # BLOQUEAR commits diretos em sandbox e main (usar workflow de release!)
    - if: '$CI_COMMIT_BRANCH == "sandbox" || $CI_COMMIT_BRANCH == "main"'
      when: never
    # Permitir outras branches (feature, fix, etc.)
    - if: '$CI_COMMIT_BRANCH'

include:
  # Include DIRETO dos arquivos específicos (SEM precisar do .gitlab-ci.yml na raiz!)
  # GitLab suporta array de files desde a versão 13.6
  - project: 'm3nura/pipelines'
    ref: main
    file:
      - '.gitlab/ci/codebase-ci-node.yml'
      - '.gitlab/deploy/codebase-preview-deploy.yml'

# Definir stages
stages:
  - build
  - deploy

# Definir variáveis do projeto
variables:
  NODE_VERSION: "20"
  ARTIFACT_PATH: "build"
  SKIP_LINT: "true"   # Pular lint
  SKIP_TESTS: "true"  # Pular testes
  ARTIFACT_NAME: "menura-documentation-portal"
  PREVIEW_URL: "https://docs.sandbox.menura.com.br"  # URL do preview deploy

# Job de build
build:
  extends: .node-build

# Job de preview deploy (manual)
preview:
  extends: .preview-deploy
  needs:
    - job: build
      artifacts: true
