# =============================================================================
# Exemplo: CI Node.js pulando lint e testes
# =============================================================================
# Este exemplo é útil para projetos como Docusaurus que não têm lint/tests.
# Copie este arquivo para a raiz do seu projeto como .gitlab-ci.yml
# =============================================================================

include:
  # Include DIRETO dos arquivos específicos (SEM precisar do .gitlab-ci.yml na raiz!)
  # GitLab suporta array de files desde a versão 13.6
  - project: 'm3nura/pipelines'
    ref: main
    file:
      - '.gitlab/ci/codebase-ci-node.yml'
      - '.gitlab/deploy/codebase-preview-deploy.yml'

# Definir stages
stages:
  - build
  - deploy

# Definir variáveis do projeto
variables:
  NODE_VERSION: "20"
  ARTIFACT_PATH: "build"
  SKIP_LINT: "true"   # Pular lint
  SKIP_TESTS: "true"  # Pular testes

# Job de build
build:
  extends: .node-build

# Job de preview deploy (manual)
preview:
  extends: .preview-deploy
  variables:
    ARTIFACT_NAME: "menura-documentation-portal"
  needs:
    - job: build
      artifacts: true
