# =============================================================================
# Exemplo: CI Node.js com Preview Deploy no GitLab
# =============================================================================
# Este exemplo mostra como incluir múltiplos arquivos específicos.
# Copie este arquivo para a raiz do seu projeto como .gitlab-ci.yml
# =============================================================================

include:
  # Include DIRETO de múltiplos arquivos específicos (GitLab 13.6+)
  - project: 'm3nura/pipelines'
    ref: main
    file:
      - '.gitlab/ci/codebase-ci-node.yml'
      - '.gitlab/deploy/codebase-preview-deploy.yml'

# Definir stages
stages:
  - test
  - build
  - deploy

# Definir variáveis do projeto
variables:
  NODE_VERSION: "20"
  ARTIFACT_PATH: "dist"
  ARTIFACT_NAME: "meu-app"  # Nome do seu projeto

# Jobs de CI (estendem templates de .gitlab/ci/codebase-ci-node.yml)
lint:
  extends: .node-lint

test:
  extends: .node-test

build:
  extends: .node-build

# Jobs de Deploy (estendem templates de .gitlab/deploy/codebase-preview-deploy.yml)
preview:
  extends: .preview-deploy
  needs:
    - job: build
      artifacts: true

stop_preview:
  extends: .stop-preview
